export const ERROR_CONSTANTS = {
  NON_AUTHORIZED: (userId: string) =>
    `THE USER ${userId} HAS NO AUTHORIZATION TO ACCESS THE TICKET`,
  TICKET_NOT_FOUND: 'TICKET_NOT_FOUND',
  MISSING_AUTHORIZATION: 'MISSING AUTHORIZATION IN HEADERS,',
};
