export const ERROR_CONSTANTS = {
  ERROR_ON_CREATE_TICKET: 'ERROR ON CREATE TICKET',
  NON_AUTHORIZED: (userId: string) =>
    `THE USER ${userId} HAS NO AUTHORIZATION TO ACCESS THE TICKET`,
  TICKET_NOT_FOUND: 'TICKET_NOT_FOUND',
  MISSING_AUTHORIZATION: 'MISSING AUTHORIZATION IN HEADERS',
  THIS_USER_HAS_NO_PERMISSION_TO_PERFORM_THIS_ACTION:
    'THIS USER HAS NO PERMISSION TO PERFORM THIS ACTION',
  USER_NOT_FOUND_ON_CREATE_TICKET: 'ERROR ON CREATE TICKET - USER NOT FOUND',
  ERROR_ON_INSERT_COMMENT: 'ERROR ON INSERT COMMENT',
};
